- name: Python
  logo: Python
  url: https://www.python.org/
  color: '#3776AB'
  projects:
    - url: https://github.com/ashleymavericks/notion-portfolio-tracker
    - url: https://github.com/ashleymavericks/notion-interactive-brokers
    - url: https://github.com/ashleymavericks/notion-habit-tracker
    - url: https://github.com/hackclubnmit/certificate-generator
    
- name: Flask
  logo: Flask
  url: https://flask.palletsprojects.com/en/2.1.x/
  color: '#000000'
  projects:
    - url: https://github.com/ashleymavericks/bitgrit-personality-api
    - url: https://github.com/ashleymavericks/tradingview-discord-middleware
    
- name: FastAPI
  logo: FastAPI
  url: https://fastapi.tiangolo.com/
  color: '##009688'
  projects:
    - url: https://github.com/ashleymavericks/strategical-trading
    - wip: true
    
- name: JavaScript
  logo: JavaScript
  url: https://javascript.info/
  color: '#F7DF1E'
  projects:
    - url: https://github.com/ashleymavericks/www
    - url: https://github.com/ashleymavericks/anuragsingh.dev
    
- name: Node.js
  logo: Node.js
  url: https://nodejs.org/en/
  color: '#339933'
  projects:
    - url: https://github.com/ashleymavericks/speaking-geo-assistant-backend
    - url: https://github.com/ashleymavericks/dietary-care
    
- name: Shell
  logo: GNU Bash
  url: https://www.gnu.org/
  color: '#4EAA25'
  projects:
    - url: https://github.com/ashleymavericks/dotfiles-public

- name: Spark AR
  logo: Spark AR
  url: https://sparkar.facebook.com/ar-studio/
  color: '#FF5C83'
  projects:
    - url: https://github.com/ashleymavericks/AR-PiZero
