- name: Python
  logo: python
  url: https://www.python.org/
  color: '#3C78A9'
  projects:
    - url: https://github.com/ashleymavericks/notion-portfolio-tracker
    - url: https://github.com/ashleymavericks/bitgrit-personality-api
    - url: https://github.com/hackclubnmit/certificate-generator
    
- name: JS/TS
  logo: javascript
  url: https://www.typescriptlang.org/
  color: '#3878C6'
  projects:
    - url: hhttps://github.com/ashleymavericks/Speaking-Geo-Assistant-Backend
    
- name: Node.js
  logo: node.js
  url: https://nodejs.org/en/
  color: '#47d147'
  logoColor: FFFFFF
  projects:
    - url: https://github.com/ashleymavericks/Civil-Services-Assistant
    - url: https://github.com/ashleymavericks/Dietary-Care

- name: React
  logo: React
  url: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5
  color: '#ff751a'
  projects:
    - url: https://github.com/ashleymavericks/www
